<a href="https://colab.research.google.com/github/johansB08/labsSeminario/blob/main/Laboratorio2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas vs Polars vs Spark vs Dask
[Author: Johan Benavides](https://github.com/johansB08/labsSeminario)

Inspired in: https://www.youtube.com/watch?v=mi9f9zOaqM8

Original data: Kaggle

This jupyter notebook is designed to study and compare different tools to read and manipulate data; to be used in the data undertanding phase. The corresponding explanations will be given directly in class, therefore the material isn't autoexplained. DonÂ´t forget ask me for the access to the data. And, please, give credits to the original author's idea and, if consider, also to me.

_Updated: June 20th, 2023_

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Playing with pandas

In [ ]:
import pandas as pd
flights_file1 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2018.parquet"
flights_file2 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2019.parquet"
flights_file3 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2020.parquet"
#flights_file4 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2021.parquet"
#flights_file5 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2022.parquet"
df1 = pd.read_parquet(flights_file1)
df2 = pd.read_parquet(flights_file2)
df3 = pd.read_parquet(flights_file3)
#df4 = pd.read_parquet(flights_file4)
#df5 = pd.read_parquet(flights_file5)

In [ ]:
df = pd.concat([df2, df4])
#df = df2

In [ ]:
# %%timeit

df_agg = df.groupby(['Airline','Year'])[["DepDelayMinutes", "ArrDelayMinutes"]].agg(
    ["mean", "sum", "max"]
)
df_agg = df_agg.reset_index()
df_agg.to_parquet("temp_pandas.parquet")

In [ ]:
!ls -GFlash temp_pandas.parquet

12K -rw-r--r-- 1 root 10K Jul  3 22:00 temp_pandas.parquet

In [ ]:
pd.read_parquet('temp_pandas.parquet')

                                      Airline  Year DepDelayMinutes  \
                                                               mean
0                 Air Wisconsin Airlines Corp  2020        8.583725
1                 Air Wisconsin Airlines Corp  2021       16.553045
2                        Alaska Airlines Inc.  2020        5.818328
3                        Alaska Airlines Inc.  2021        8.575051
4                               Allegiant Air  2020       12.825575
5                               Allegiant Air  2021       19.634153
6                      American Airlines Inc.  2020        7.624477
7                      American Airlines Inc.  2021       14.527001
8                 Capital Cargo International  2020        7.665063
9                 Capital Cargo International  2021        9.970415
10                                Comair Inc.  2020       10.068723
11                                Comair Inc.  2021       10.456981
12  Commutair Aka Champlain Enterprises, Inc.  2020       12.266858
13  Commutair Aka Champlain Enterprises, Inc.  2021       21.680783
14                           Compass Airlines  2020        8.215550
15                       Delta Air Lines Inc.  2020        5.581694
16                       Delta Air Lines Inc.  2021        8.852645
17                       Empire Airlines Inc.  2020        6.861561
18                       Empire Airlines Inc.  2021        5.241071
19                          Endeavor Air Inc.  2020        5.653603
20                          Endeavor Air Inc.  2021        6.556770
21                                  Envoy Air  2020        6.685444
22                                  Envoy Air  2021        9.976197
23                   ExpressJet Airlines Inc.  2020        6.396004
24                     Frontier Airlines Inc.  2020        7.398021
25                     Frontier Airlines Inc.  2021       15.954884
26   GoJet Airlines, LLC d/b/a United Express  2020        8.309550
27   GoJet Airlines, LLC d/b/a United Express  2021       15.667626
28                     Hawaiian Airlines Inc.  2020        3.592000
29                     Hawaiian Airlines Inc.  2021        5.219030
30                                Horizon Air  2020        4.849894
31                                Horizon Air  2021        7.007160
32                            JetBlue Airways  2020        8.213825
33                            JetBlue Airways  2021       20.311685
34                         Mesa Airlines Inc.  2020        9.662425
35                         Mesa Airlines Inc.  2021       18.057408
36                          Republic Airlines  2020        5.224466
37                          Republic Airlines  2021        9.454969
38                      SkyWest Airlines Inc.  2020        8.671988
39                      SkyWest Airlines Inc.  2021       13.931217
40                     Southwest Airlines Co.  2020        4.116316
41                     Southwest Airlines Co.  2021       14.802173
42                           Spirit Air Lines  2020        7.809889
43                           Spirit Air Lines  2021       14.462256
44                      Trans States Airlines  2020       13.739364
45                      United Air Lines Inc.  2020        6.925499
46                      United Air Lines Inc.  2021       12.196467

                       ArrDelayMinutes
           sum     max            mean         sum     max
0     433315.0  1460.0        8.982529    452450.0  1439.0
1    1290194.0  1421.0       17.327440   1346602.0  1416.0
2     772930.0   823.0        6.365082    843157.0   788.0
3    1594042.0   938.0        9.507075   1761718.0   934.0
4    1080016.0  1648.0       13.331111   1115734.0  1645.0
5    2200694.0  1995.0       21.274423   2378523.0  1990.0
6    4084097.0  3890.0        7.861155   4202644.0  3864.0
7   10463784.0  3095.0       13.793588   9901465.0  3089.0
8     512969.0  1482.0        8.427212    561522.0  1470.0
9     978327.0  1808.0       10.777159   1052853.0  1797.0
10   1798294.0  1919.0       10.686808   1903235.0  1888.0
11   2305482.0  1838.0       10.883368   2392654.0  1869.0
12    385670.0  1557.0       13.438158    421340.0  1555.0
13   1609126.0  1488.0       23.407156   1729625.0  1512.0
14    120670.0  1431.0        8.641498    126693.0  1412.0
15   3083283.0  1195.0        6.209070   3424414.0  1193.0
16   6590555.0  1234.0        8.509149   6322706.0  1272.0
17     32613.0   274.0        7.028136     33222.0   272.0
18       587.0    85.0        5.250000       588.0    81.0
19   1156405.0  2579.0        5.877866   1200707.0  2560.0
20   1743832.0  1915.0        6.729974   1786613.0  1937.0
21   1339382.0  2248.0        8.417206   1682490.0  2238.0
22   2497092.0  1783.0       10.835396   2702337.0  1761.0
23    308249.0  1357.0        7.443095    357797.0  1338.0
24    640062.0   645.0        7.330406    633479.0   638.0
25   2158281.0  1335.0       16.033348   2165015.0  1356.0
26    304786.0  1408.0        8.336411    305196.0  1382.0
27    909443.0  1653.0       16.756907    969806.0  1653.0
28    137491.0  1484.0        4.092661    156487.0  1481.0
29    314671.0  1757.0        5.318475    320369.0  1762.0
30    445133.0   775.0        5.351232    489932.0   758.0
31    768216.0   862.0        7.465947    816476.0   836.0
32   1118838.0  1135.0        8.503231   1155334.0  1153.0
33   4052628.0  1834.0       19.945458   3960789.0  1815.0
34   1236887.0  1890.0       10.344427   1320704.0  1884.0
35   2801336.0  2069.0       18.249950   2820621.0  2056.0
36   1093533.0  1352.0        5.824160   1216865.0  1381.0
37   3096493.0  1629.0       10.325604   3371609.0  1613.0
38   4963057.0  2327.0        8.718970   4976457.0  2308.0
39  10312207.0  2312.0       14.253187  10517227.0  2302.0
40   3637115.0   602.0        3.372148   2975631.0   597.0
41  15413518.0   975.0       12.613220  13102108.0   630.0
42   1032194.0  1339.0        7.758486   1023290.0  1262.0
43   2686740.0  1503.0       14.593450   2703962.0  1519.0
44    235108.0  1390.0       14.784864    252008.0  1366.0
45   1978518.0  1471.0        6.766355   1929514.0  1503.0
46   5377081.0  1581.0       12.238722   5380803.0  1655.0

In [ ]:
pd.read_parquet('temp_pandas.parquet').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   (Airline, )              47 non-null     object
 1   (Year, )                 47 non-null     int64
 2   (DepDelayMinutes, mean)  47 non-null     float64
 3   (DepDelayMinutes, sum)   47 non-null     float64
 4   (DepDelayMinutes, max)   47 non-null     float64
 5   (ArrDelayMinutes, mean)  47 non-null     float64
 6   (ArrDelayMinutes, sum)   47 non-null     float64
 7   (ArrDelayMinutes, max)   47 non-null     float64
dtypes: float64(6), int64(1), object(1)
memory usage: 3.1+ KB

## Playing with Polars

In [ ]:
import polars as pl

In [ ]:
#flights_file1 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2018.parquet"
#flights_file2 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2019.parquet"
flights_file3 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2020.parquet"
#flights_file4 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2022.parquet"
#flights_file5 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2022.parquet"
#df1 = pl.scan_parquet(flights_file1)
#df2 = pl.scan_parquet(flights_file2)
df3 = pl.scan_parquet(flights_file3)
#df4 = pl.scan_parquet(flights_file4)
#df5 = pl.scan_parquet(flights_file5)

In [ ]:
 %%timeit

df_polars = (
    pl.concat([df1, df2, df3, df4, df5])
    .groupby(['Airline', 'Year'])
    .agg([
        pl.col("DepDelayMinutes").mean().alias("avg_dep_delay"),
        pl.col("DepDelayMinutes").sum().alias("sum_dep_delay"),
        pl.col("DepDelayMinutes").max().alias("max_dep_delay"),
        pl.col("ArrDelayMinutes").mean().alias("avg_arr_delay"),
        pl.col("ArrDelayMinutes").sum().alias("sum_arr_delay"),
        pl.col("ArrDelayMinutes").max().alias("max_arr_delay"),
      ])
).collect()

df_polars.write_parquet('temp_polars.parquet')

<magic-timeit>:3: DeprecationWarning: `groupby` is deprecated. It has been renamed to `group_by`.

9.45 s Â± 739 ms per loop (mean Â± std. dev. of 7 runs, 1 loop each)

In [ ]:
!ls -GFlash temp_polars.parquet

8.0K -rw-r--r-- 1 root 8.0K Jul  3 23:39 temp_polars.parquet

## Playing with PySpark

In [ ]:
!pip install pyspark

Collecting pyspark
  Downloading pyspark-3.5.1.tar.gz (317.0 MB)
     ââââââââââââââââââââââââââââââââââââââââ 317.0/317.0 MB 3.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.1-py2.py3-none-any.whl size=317488491 sha256=a6e6f63632fe96af20d831a964b8ee52c1f1955944f3020c67d89d99a90b8727
  Stored in directory: /root/.cache/pip/wheels/80/1d/60/2c256ed38dddce2fdd93be545214a63e02fbd8d74fb0b7f3a6
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.5.1

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import avg, max, sum, concat

In [ ]:
spark = SparkSession.builder.master("local[1]").appName("airline-example").getOrCreate()

In [ ]:
flights_file1 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2018.parquet"
flights_file2 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2019.parquet"
flights_file3 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2020.parquet"
flights_file4 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2021.parquet"
flights_file5 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2022.parquet"

In [ ]:
df_spark1 = spark.read.parquet(flights_file1)
df_spark2 = spark.read.parquet(flights_file2)
df_spark3 = spark.read.parquet(flights_file3)
df_spark4 = spark.read.parquet(flights_file4)
df_spark5 = spark.read.parquet(flights_file5)

In [ ]:
df_spark = df_spark1 # Initialize df_spark with the first DataFrame
df_spark = df_spark.union(df_spark2)
df_spark = df_spark.union(df_spark3)
df_spark = df_spark.union(df_spark4)
df_spark = df_spark.union(df_spark5)

In [ ]:
 %%timeit

df_spark_agg = df_spark.groupby("Airline", "Year").agg(
    avg("ArrDelayMinutes").alias('avg_arr_delay'),
    sum("ArrDelayMinutes").alias('sum_arr_delay'),
    max("ArrDelayMinutes").alias('max_arr_delay'),
    avg("DepDelayMinutes").alias('avg_dep_delay'),
    sum("DepDelayMinutes").alias('sum_dep_delay'),
    max("DepDelayMinutes").alias('max_dep_delay'),
)
df_spark_agg.write.mode('overwrite').parquet('temp_spark.parquet')

7.34 s Â± 883 ms per loop (mean Â± std. dev. of 7 runs, 1 loop each)

In [ ]:
!ls -GFlash temp_pyspark.parquet

ls: cannot access 'temp_pyspark.parquet': No such file or directory

## Playing with dask

In [ ]:
import pandas as pd
import dask.dataframe as dd
flights_file1 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2018.parquet"
flights_file2 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2019.parquet"
flights_file3 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2020.parquet"
flights_file4 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2021.parquet"
flights_file5 = "/content/drive/MyDrive/SeminarioB/Taller2/Combined_Flights_2022.parquet"
df1 = dd.read_parquet(flights_file1)
df2 = dd.read_parquet(flights_file2)
df3 = dd.read_parquet(flights_file3)
df4 = dd.read_parquet(flights_file4)
df5 = dd.read_parquet(flights_file5)

In [ ]:
df = dd.concat([df1, df2, df3, df4, df5])

In [ ]:
print(df.compute())

In [ ]:
df = df.compute()

In [ ]:
# %%timeit

df_agg = df.groupby(['Airline','Year'])[["DepDelayMinutes", "ArrDelayMinutes"]].agg(
    ["mean", "sum", "max"]
)
df_agg = df_agg.reset_index()
df_agg.to_parquet("temp_dask.parquet")

In [ ]:
!ls -GFlash temp_pandas.parquet

ls: cannot access 'temp_pandas.parquet': No such file or directory

In [ ]:
pd.read_parquet('temp_dask.parquet').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   (Airline, )              47 non-null     string
 1   (Year, )                 47 non-null     int64
 2   (DepDelayMinutes, mean)  47 non-null     float64
 3   (DepDelayMinutes, sum)   47 non-null     float64
 4   (DepDelayMinutes, max)   47 non-null     float64
 5   (ArrDelayMinutes, mean)  47 non-null     float64
 6   (ArrDelayMinutes, sum)   47 non-null     float64
 7   (ArrDelayMinutes, max)   47 non-null     float64
dtypes: float64(6), int64(1), string(1)
memory usage: 3.1 KB

In [ ]:
pd.read_parquet('temp_dask.parquet')

                                      Airline  Year DepDelayMinutes  \
                                                               mean
0                 Air Wisconsin Airlines Corp  2020        8.583725
1                 Air Wisconsin Airlines Corp  2021       16.553045
2                        Alaska Airlines Inc.  2020        5.818328
3                        Alaska Airlines Inc.  2021        8.575051
4                               Allegiant Air  2020       12.825575
5                               Allegiant Air  2021       19.634153
6                      American Airlines Inc.  2020        7.624477
7                      American Airlines Inc.  2021       14.527001
8                 Capital Cargo International  2020        7.665063
9                 Capital Cargo International  2021        9.970415
10                                Comair Inc.  2020       10.068723
11                                Comair Inc.  2021       10.456981
12  Commutair Aka Champlain Enterprises, Inc.  2020       12.266858
13  Commutair Aka Champlain Enterprises, Inc.  2021       21.680783
14                           Compass Airlines  2020        8.215550
15                       Delta Air Lines Inc.  2020        5.581694
16                       Delta Air Lines Inc.  2021        8.852645
17                       Empire Airlines Inc.  2020        6.861561
18                       Empire Airlines Inc.  2021        5.241071
19                          Endeavor Air Inc.  2020        5.653603
20                          Endeavor Air Inc.  2021        6.556770
21                                  Envoy Air  2020        6.685444
22                                  Envoy Air  2021        9.976197
23                   ExpressJet Airlines Inc.  2020        6.396004
24                     Frontier Airlines Inc.  2020        7.398021
25                     Frontier Airlines Inc.  2021       15.954884
26   GoJet Airlines, LLC d/b/a United Express  2020        8.309550
27   GoJet Airlines, LLC d/b/a United Express  2021       15.667626
28                     Hawaiian Airlines Inc.  2020        3.592000
29                     Hawaiian Airlines Inc.  2021        5.219030
30                                Horizon Air  2020        4.849894
31                                Horizon Air  2021        7.007160
32                            JetBlue Airways  2020        8.213825
33                            JetBlue Airways  2021       20.311685
34                         Mesa Airlines Inc.  2020        9.662425
35                         Mesa Airlines Inc.  2021       18.057408
36                          Republic Airlines  2020        5.224466
37                          Republic Airlines  2021        9.454969
38                      SkyWest Airlines Inc.  2020        8.671988
39                      SkyWest Airlines Inc.  2021       13.931217
40                     Southwest Airlines Co.  2020        4.116316
41                     Southwest Airlines Co.  2021       14.802173
42                           Spirit Air Lines  2020        7.809889
43                           Spirit Air Lines  2021       14.462256
44                      Trans States Airlines  2020       13.739364
45                      United Air Lines Inc.  2020        6.925499
46                      United Air Lines Inc.  2021       12.196467

                       ArrDelayMinutes
           sum     max            mean         sum     max
0     433315.0  1460.0        8.982529    452450.0  1439.0
1    1290194.0  1421.0       17.327440   1346602.0  1416.0
2     772930.0   823.0        6.365082    843157.0   788.0
3    1594042.0   938.0        9.507075   1761718.0   934.0
4    1080016.0  1648.0       13.331111   1115734.0  1645.0
5    2200694.0  1995.0       21.274423   2378523.0  1990.0
6    4084097.0  3890.0        7.861155   4202644.0  3864.0
7   10463784.0  3095.0       13.793588   9901465.0  3089.0
8     512969.0  1482.0        8.427212    561522.0  1470.0
9     978327.0  1808.0       10.777159   1052853.0  1797.0
10   1798294.0  1919.0       10.686808   1903235.0  1888.0
11   2305482.0  1838.0       10.883368   2392654.0  1869.0
12    385670.0  1557.0       13.438158    421340.0  1555.0
13   1609126.0  1488.0       23.407156   1729625.0  1512.0
14    120670.0  1431.0        8.641498    126693.0  1412.0
15   3083283.0  1195.0        6.209070   3424414.0  1193.0
16   6590555.0  1234.0        8.509149   6322706.0  1272.0
17     32613.0   274.0        7.028136     33222.0   272.0
18       587.0    85.0        5.250000       588.0    81.0
19   1156405.0  2579.0        5.877866   1200707.0  2560.0
20   1743832.0  1915.0        6.729974   1786613.0  1937.0
21   1339382.0  2248.0        8.417206   1682490.0  2238.0
22   2497092.0  1783.0       10.835396   2702337.0  1761.0
23    308249.0  1357.0        7.443095    357797.0  1338.0
24    640062.0   645.0        7.330406    633479.0   638.0
25   2158281.0  1335.0       16.033348   2165015.0  1356.0
26    304786.0  1408.0        8.336411    305196.0  1382.0
27    909443.0  1653.0       16.756907    969806.0  1653.0
28    137491.0  1484.0        4.092661    156487.0  1481.0
29    314671.0  1757.0        5.318475    320369.0  1762.0
30    445133.0   775.0        5.351232    489932.0   758.0
31    768216.0   862.0        7.465947    816476.0   836.0
32   1118838.0  1135.0        8.503231   1155334.0  1153.0
33   4052628.0  1834.0       19.945458   3960789.0  1815.0
34   1236887.0  1890.0       10.344427   1320704.0  1884.0
35   2801336.0  2069.0       18.249950   2820621.0  2056.0
36   1093533.0  1352.0        5.824160   1216865.0  1381.0
37   3096493.0  1629.0       10.325604   3371609.0  1613.0
38   4963057.0  2327.0        8.718970   4976457.0  2308.0
39  10312207.0  2312.0       14.253187  10517227.0  2302.0
40   3637115.0   602.0        3.372148   2975631.0   597.0
41  15413518.0   975.0       12.613220  13102108.0   630.0
42   1032194.0  1339.0        7.758486   1023290.0  1262.0
43   2686740.0  1503.0       14.593450   2703962.0  1519.0
44    235108.0  1390.0       14.784864    252008.0  1366.0
45   1978518.0  1471.0        6.766355   1929514.0  1503.0
46   5377081.0  1581.0       12.238722   5380803.0  1655.0

## Read Results

In [ ]:
import pandas as pd

In [ ]:
agg_pandas = pd.read_parquet('temp_pandas.parquet')
agg_polars = pd.read_parquet('temp_polars.parquet')
agg_spark = pd.read_parquet('temp_spark.parquet')
agg_dask = pd.read_parquet('temp_dask.parquet')

In [ ]:
agg_pandas.shape, agg_polars.shape, agg_spark.shape, agg_dask.shape

((26, 8), (122, 8), (122, 8), (26, 8))

In [ ]:
agg_pandas.sort_values(['Airline','Year']).head()

                       Airline  Year DepDelayMinutes                      \
                                                mean         sum     max
0  Air Wisconsin Airlines Corp  2019       16.868511   1742281.0  1690.0
1         Alaska Airlines Inc.  2019        9.836041   2576246.0  1117.0
2                Allegiant Air  2019       14.678433   1536876.0  1979.0
3       American Airlines Inc.  2019       14.895515  13814816.0  2315.0
4  Capital Cargo International  2019       11.525332   1367642.0  1182.0

  ArrDelayMinutes
             mean         sum     max
0       17.610384   1811545.0  1707.0
1       10.787284   2815643.0  1087.0
2       15.556524   1624770.0  1966.0
3       15.251863  14096412.0  2350.0
4       12.489465   1474806.0  1190.0

In [ ]:
agg_polars.sort_values(['Airline','Year']).head()

,Airline,Year,avg_dep_delay,sum_dep_delay,max_dep_delay,avg_arr_delay,sum_arr_delay,max_arr_delay
28,Air Wisconsin Airlines Corp,2018,16.753459,1606774.0,1296.0,17.881934,1708887.0,1292.0
54,Air Wisconsin Airlines Corp,2019,16.868511,1742281.0,1690.0,17.610384,1811545.0,1707.0
106,Air Wisconsin Airlines Corp,2020,8.583725,433315.0,1460.0,8.982529,452450.0,1439.0
6,Air Wisconsin Airlines Corp,2021,16.553045,1290194.0,1421.0,17.327440,1346602.0,1416.0
67,Air Wisconsin Airlines Corp,2022,13.124801,510581.0,1355.0,13.340409,517261.0,1353.0

In [ ]:
agg_spark.sort_values(['Airline','Year']).head()

,Airline,Year,avg_arr_delay,sum_arr_delay,max_arr_delay,avg_dep_delay,sum_dep_delay,max_dep_delay
0,Air Wisconsin Airlines Corp,2018,17.881934,1708887.0,1292.0,16.753459,1606774.0,1296.0
48,Air Wisconsin Airlines Corp,2019,17.610384,1811545.0,1707.0,16.868511,1742281.0,1690.0
56,Air Wisconsin Airlines Corp,2020,8.982529,452450.0,1439.0,8.583725,433315.0,1460.0
93,Air Wisconsin Airlines Corp,2021,17.327440,1346602.0,1416.0,16.553045,1290194.0,1421.0
119,Air Wisconsin Airlines Corp,2022,13.340409,517261.0,1353.0,13.124801,510581.0,1355.0

In [ ]:
agg_dask.sort_values(['Airline','Year']).head()

                       Airline  Year DepDelayMinutes                      \
                                                mean         sum     max
0  Air Wisconsin Airlines Corp  2019       16.868511   1742281.0  1690.0
1         Alaska Airlines Inc.  2019        9.836041   2576246.0  1117.0
2                Allegiant Air  2019       14.678433   1536876.0  1979.0
3       American Airlines Inc.  2019       14.895515  13814816.0  2315.0
4  Capital Cargo International  2019       11.525332   1367642.0  1182.0

  ArrDelayMinutes
             mean         sum     max
0       17.610384   1811545.0  1707.0
1       10.787284   2815643.0  1087.0
2       15.556524   1624770.0  1966.0
3       15.251863  14096412.0  2350.0
4       12.489465   1474806.0  1190.0